services:
  backend:
    container_name: auth-nest-api
    depends_on:
      - database
    restart: always
    build:
      context: .
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
